### ISSUE TITLE
error wit binary_sensor

### ISSUE THREAD

**Issue by lotohov** [lcmchris/thesillyhome-container#1]
ValueError: cannot set a frame with no defined columns
2022-06-17 22:38:27.217056 WARNING model_executor: ------------------------------------------------------------
2022-06-17 22:39:16.249946 INFO model_executor: <--- binary_sensor.motion_sensor_158d0001d6683f is on --->
2022-06-17 22:39:16.273905 WARNING model_executor: ------------------------------------------------------------
2022-06-17 22:39:16.275041 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-17 22:39:16.277193 WARNING model_executor: Worker Ags: {'id': '1106d0c1b1c24967b5f7017ef9038914', 'name': 'model_executor', 'objectid': '203bed332a824e50ad6f56f6f148fdc8', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f7cd53460>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d0001d6683f', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-17 22:39:16.278959 WARNING model_executor: ------------------------------------------------------------
2022-06-17 22:39:16.280436 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 59, in state_handler
    current_state_base.loc[len(current_state_base)] = 0
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 716, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1682, in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1982, in _setitem_with_indexer_missing
    raise ValueError("cannot set a frame with no defined columns")
ValueError: cannot set a frame with no defined columns
2022-06-17 22:39:16.287109 WARNING model_executor: ------------------------------------------------------------
2022-06-17 22:39:30.144637 INFO model_executor: <--- binary_sensor.motion_sensor_158d000405931b is on --->
2022-06-17 22:39:30.159895 WARNING model_executor: ------------------------------------------------------------
2022-06-17 22:39:30.162621 WARNING model_executor: Unexpected error in worker for App model_executor:
2022-06-17 22:39:30.165646 WARNING model_executor: Worker Ags: {'id': '1106d0c1b1c24967b5f7017ef9038914', 'name': 'model_executor', 'objectid': '203bed332a824e50ad6f56f6f148fdc8', 'type': 'state', 'function': <bound method ModelExecutor.state_handler of <model_executor.ModelExecutor object at 0x7f7cd53460>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_sensor_158d000405931b', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2022-06-17 22:39:30.168911 WARNING model_executor: ------------------------------------------------------------
2022-06-17 22:39:30.172593 WARNING model_executor: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 59, in state_handler
    current_state_base.loc[len(current_state_base)] = 0
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 716, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1682, in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1982, in _setitem_with_indexer_missing
    raise ValueError("cannot set a frame with no defined columns")
ValueError: cannot set a frame with no defined columns

**Comment by lcmchris** [comment]
Hi @lotohov 
Could you zip me your config file and the /thesillyhome_src/data/all_states.csv from the container? That would help me loads for triaging!
