### ISSUE TITLE
ERROR:root:uncaught exception

### ISSUE THREAD

**Issue by benwainwright** [lcmchris/thesillyhome-container#45]
Interesting project. Tried to set it up and got this immediately

```
Starting to parse DB data
ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "DESCRIBE": syntax error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
2023-03-19 20:02:55,122 - root - ERROR - Uncaught exception
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py", line 22, in <module>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    homedb().send_data()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/parse_data.py", line 40, in __init__
    ) = self.check_schema()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/parse_data.py", line 46, in check_schema
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "DESCRIBE": syntax error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    desc_schema = pd.read_sql(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 591, in read_sql
    return pandas_sql.read_query(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1561, in read_query
    result = self.execute(*args)
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1406, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
    return self._exec_driver_sql(
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/main.py", line 22, in <module>
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DESCRIBE": syntax error
[SQL: DESCRIBE homeassistant.states;]
    homedb().send_data()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/parse_data.py", line 40, in __init__
    ) = self.check_schema()
  File "/thesillyhome_src/thesillyhome/src/thesillyhome/model_creator/parse_data.py", line 46, in check_schema
    desc_schema = pd.read_sql(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 591, in read_sql
    return pandas_sql.read_query(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1561, in read_query
    result = self.execute(*args)
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1406, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
    return self._exec_driver_sql(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DESCRIBE": syntax error
[SQL: DESCRIBE homeassistant.states;]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Model generation failed.
```

This is my config

```
- db_password: password
  db_username: homeassistant
  db_host: 192.168.1.177
  db_port: "3306"
  db_database: home-assistant_v2.db
  db_type: sqlite
```

What's slightly confusing is the stack trace doesn't appear to relate that strongly to the code in your repository so it was quite hard for me to debug...

**Comment by lcmchris** [comment]
This should be fixed with the latest PR.
