### ISSUE TITLE
Unexpected error running initialize() for model_executor

### ISSUE THREAD

**Issue by benwainwright** [lcmchris/thesillyhome-container#46]
Got another error in my logs. Wasn't sure if this was a problem or not

```
2023-03-19 23:38:34.590968 WARNING model_executor: ------------------------------------------------------------
2023-03-19 23:38:34.592787 WARNING model_executor: Unexpected error running initialize() for model_executor
2023-03-19 23:38:34.593283 WARNING model_executor: ------------------------------------------------------------
2023-03-19 23:38:34.598152 WARNING model_executor: Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/opt/venv/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 23, in initialize
    pd.read_parquet(f"{self.model_path}/X_train_entity_ids.parquet")[
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/parquet.py", line 501, in read_parquet
    return impl.read(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/parquet.py", line 349, in read
    handles = get_handle(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/common.py", line 866, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/thesillyhome_src/data/model/1/X_train_entity_ids.parquet'
2023-03-19 23:38:34.598613 WARNING model_executor: ------------------------------------------------------------
2023-03-19 23:38:34.601611 INFO AppDaemon: App initialization complete
```

**Comment by benwainwright** [comment]
Yes this crash is continuing to happen :(

**Comment by lcmchris** [comment]
This should be fixed with the latest PR. The schema changed from HA side.
