### ISSUE TITLE
No such file or directory: '/thesillyhome_src/data/model/1/X_train_entity_ids.parquet'

### ISSUE THREAD

**Issue by nilsgroemke** [lcmchris/thesillyhome-container#59]
Hi, 

installed the addon through repo directly in Homeassistant.
After startup it takes some time and then the following error appears:

2023-04-27 16:28:19,246 - root - INFO - Completed training job. Model saved.
Starting Appdaemon
2023-04-27 15:28:19.833975 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2023-04-27 15:28:19.834112 INFO AppDaemon: Python version is 3.9.16
2023-04-27 15:28:19.834189 INFO AppDaemon: Configuration read from: /thesillyhome_src/appdaemon/appdaemon.yaml
2023-04-27 15:28:19.834317 INFO AppDaemon: Added log: AppDaemon
2023-04-27 15:28:19.834398 INFO AppDaemon: Added log: Error
2023-04-27 15:28:19.834485 INFO AppDaemon: Added log: Access
2023-04-27 15:28:19.834552 INFO AppDaemon: Added log: Diag
2023-04-27 15:28:19.844991 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-04-27 15:28:19.944121 INFO HASS: HASS Plugin Initializing
2023-04-27 15:28:19.944301 INFO HASS: HASS Plugin initialization complete
2023-04-27 15:28:19.944588 INFO AppDaemon: HTTP is disabled
2023-04-27 15:28:19.952304 INFO HASS: Connected to Home Assistant 2023.4.5
2023-04-27 15:28:19.959523 INFO AppDaemon: App 'model_executor' added
2023-04-27 15:28:19.960902 INFO AppDaemon: Found 1 total apps
2023-04-27 15:28:19.961175 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2023-04-27 15:28:19.990949 INFO HASS: Evaluating startup conditions
2023-04-27 15:28:19.997378 INFO HASS: Startup condition met: hass state=RUNNING
2023-04-27 15:28:19.997622 INFO HASS: All startup conditions met
2023-04-27 15:28:20.017752 INFO AppDaemon: Got initial state from namespace default
2023-04-27 15:28:21.967156 INFO AppDaemon: Scheduler running in realtime
2023-04-27 15:28:21.969979 INFO AppDaemon: Adding /thesillyhome_src/appdaemon/apps to module import path
2023-04-27 15:28:21.972676 INFO AppDaemon: Loading App Module: /thesillyhome_src/appdaemon/apps/model_executor.py
2023-04-27 15:28:23.390739 INFO AppDaemon: Initializing app model_executor using class ModelExecutor from module model_executor
2023-04-27 15:28:23.431073 WARNING model_executor: ------------------------------------------------------------
2023-04-27 15:28:23.431616 WARNING model_executor: Unexpected error running initialize() for model_executor
2023-04-27 15:28:23.431765 WARNING model_executor: ------------------------------------------------------------
2023-04-27 15:28:23.433157 WARNING model_executor: Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/opt/venv/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/thesillyhome_src/appdaemon/apps/model_executor.py", line 23, in initialize
    pd.read_parquet(f"{self.model_path}/X_train_entity_ids.parquet")[
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/parquet.py", line 501, in read_parquet
    return impl.read(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/parquet.py", line 349, in read
    handles = get_handle(
  File "/opt/venv/lib/python3.9/site-packages/pandas/io/common.py", line 866, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/thesillyhome_src/data/model/1/X_train_entity_ids.parquet'
2023-04-27 15:28:23.433320 WARNING model_executor: ------------------------------------------------------------
2023-04-27 15:28:23.433849 INFO AppDaemon: App initialization complete

**Comment by Lightningpicture** [comment]
The Problem is a change on Database.
Next Update, do fix it.

**Comment by PhillipRt** [comment]
@Lightningpicture Update not released? I am still getting the error
